# Generated by Django 4.0.6 on 2023-04-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_rename_dob_userreg1_dob_rename_email_userreg1_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cdur', models.CharField(max_length=30)),
                ('cfee', models.IntegerField()),
                ('csyllabus', models.CharField(max_length=30)),
                ('cregdob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='userReg1',
        ),
        migrations.DeleteModel(
            name='userReg2',
        ),
    ]
