# Generated by Django 4.0.6 on 2023-04-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_coursereg_delete_userreg1_delete_userreg2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereg',
            old_name='cdur',
            new_name='batchday',
        ),
        migrations.RenameField(
            model_name='coursereg',
            old_name='csyllabus',
            new_name='cbatch',
        ),
        migrations.RenameField(
            model_name='coursereg',
            old_name='cregdob',
            new_name='startdate',
        ),
        migrations.RemoveField(
            model_name='coursereg',
            name='cfee',
        ),
    ]
