# Generated by Django 4.0.6 on 2023-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_courseapply_coursereg1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='password',
            field=models.CharField(default=1.0, max_length=30),
            preserve_default=False,
        ),
    ]
