# Generated by Django 4.0.6 on 2023-04-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_userreg_rpwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='rpwd',
        ),
    ]
