# Generated by Django 4.0.6 on 2023-04-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_remove_userreg_rpwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='password',
            new_name='passw',
        ),
    ]
