# Generated by Django 4.0.6 on 2023-04-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0010_rename_password_userreg_passw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='passw',
            new_name='password',
        ),
    ]
