# Generated by Django 4.0.6 on 2023-04-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0012_userreg_repw'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='uid',
            field=models.IntegerField(default=1.0),
            preserve_default=False,
        ),
    ]
