# Generated by Django 4.0.6 on 2023-04-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0013_userreg_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
