# Generated by Django 4.0.6 on 2023-04-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0016_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
