# Generated by Django 4.0.6 on 2023-05-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0017_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='cupload',
            field=models.FileField(null=True, upload_to='cupload/'),
        ),
    ]
