# Generated by Django 4.0.6 on 2023-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0018_coursereg_cupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='cprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
