# Generated by Django 4.0.6 on 2023-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0020_alter_coursereg_cprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereg',
            name='cupload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
