# Generated by Django 4.0.6 on 2023-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0022_alter_coursereg_cupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='f_name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
