# Generated by Django 4.0.6 on 2023-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0025_remove_coursereg_f_name_alter_coursereg_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
