# Generated by Django 4.0.6 on 2023-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0029_alter_coursereg_cupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereg',
            name='cupload',
        ),
        migrations.AddField(
            model_name='coursereg',
            name='cimg',
            field=models.ImageField(null=True, upload_to='cimg/'),
        ),
    ]
