# Generated by Django 4.0.6 on 2023-05-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0030_remove_coursereg_cupload_coursereg_cimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereg',
            name='fname',
        ),
    ]
