# Generated by Django 4.0.6 on 2023-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0031_remove_coursereg_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereg',
            name='cimg',
            field=models.ImageField(default='media/cimg/29493.jpg', upload_to='cimg/'),
        ),
    ]
