# Generated by Django 4.0.6 on 2023-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0032_alter_coursereg_cimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereg',
            name='cimg',
            field=models.ImageField(upload_to='cimg/'),
        ),
    ]
