# Generated by Django 4.0.6 on 2023-05-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0035_coursereg_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereg',
            name='video_url',
        ),
    ]
