# Generated by Django 4.0.6 on 2023-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0037_coursereg_cpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereg',
            name='cpdf',
            field=models.FileField(null=True, upload_to='cpdf/'),
        ),
    ]
