# Generated by Django 4.0.6 on 2023-05-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0039_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_choice',
            field=models.CharField(max_length=200),
        ),
    ]
