# Generated by Django 4.0.6 on 2023-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0040_alter_quizquestion_correct_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='quiz_subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
