# Generated by Django 4.0.6 on 2023-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0041_quizquestion_quiz_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminemail', models.CharField(max_length=30)),
                ('adminpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
