# Generated by Django 4.0.6 on 2023-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0043_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default='yes it is present'),
        ),
    ]
