# Generated by Django 4.0.6 on 2023-05-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0045_remove_attendance_student_attendance_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
