# Generated by Django 4.0.6 on 2023-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0046_remove_attendance_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_absent',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
