# Generated by Django 4.0.6 on 2023-05-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0047_remove_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
